apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: hostel
  labels:
    role: api
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: api
          image: public.ecr.aws/l9g7c8b6/hostel-backend:latest
          imagePullPolicy: Always
          env:
            - name: PGHOST
              value: postgres
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /ok
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ok
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
