name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: nav to backend
        run: cd backend
      
      - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: prithvirajawatade/backend
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Update Kubernetes Deployment
      #   run: kubectl set image deployment/your-deployment-name container-name=yourusername/yourimage:latest
      #   env:
      #     KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
